//
// Created by sigsegv on 6/8/21.
//

#ifndef JEOKERNEL_KEYBOARD_H
#define JEOKERNEL_KEYBOARD_H

#define KEYBOARD_CODE_BIT_RELEASE    0x8000
#define KEYBOARD_CODE_BIT_SCROLLLOCK 0x4000
#define KEYBOARD_CODE_BIT_CAPSLOCK   0x2000
#define KEYBOARD_CODE_BIT_NUMLOCK    0x1000

#define KEYBOARD_CODE_MASK           0x0FFF

#define KEYBOARD_CODE_EXTENDED    0x0100

#define KEYBOARD_CODE_PRINTSCREEN 0x0200
#define KEYBOARD_CODE_PAUSE       (0x0201 | KEYBOARD_CODE_BIT_RELEASE)

#endif //JEOKERNEL_KEYBOARD_H
