//
// Created by sigsegv on 25.04.2021.
//

#ifndef JEOKERNEL_KERNELCONFIG_H
#define JEOKERNEL_KERNELCONFIG_H

#define NORMAL_STACK_SIZE 65536
//#define OHCI_DEBUGPRINTS_ENDPOINTS

#endif //JEOKERNEL_KERNELCONFIG_H
