//
// Created by sigsegv on 25.04.2021.
//

#ifndef JEOKERNEL_KERNELCONFIG_H
#define JEOKERNEL_KERNELCONFIG_H

#define NORMAL_STACK_SIZE 65536
//#define OHCI_DEBUGPRINTS_ENDPOINTS
#define ACPICA_MALLOC_ZERO
#define MALLOC_INIT_POISON
//#define MALLOC_INIT_ZERO
#define FREE_MEM_POISON
//#define DISABLE_FREE_MEM
//#define DELAY_FREE_MEM 256

#endif //JEOKERNEL_KERNELCONFIG_H
